image1Path = '../resources/v1.jpg'
image2Path = '../resources/v2.jpg'
image3Path = '../resources/v3.jpg'
image4Path = '../resources/v4.jpg'
image5Path = '../resources/v5.jpg'
image6Path = '../resources/v6.jpg'
image7Path = '../resources/v7.jpg'
image8Path = '../resources/v8.jpg'
image9Path = '../resources/v9.jpg'
image10Path = '../resources/v10.jpg'
image11Path = '../resources/v11.jpg'
image12Path = '../resources/v12.jpg'
image13Path = '../resources/v13.jpg'
image14Path = '../resources/v14.jpg'
image15Path = '../resources/v15.jpg'
maskPath = '../resources/mask.jpg'

mode_dir = 'dir'
mode_file = 'file'

resize_height = 700
